import JSZip from "jszip";

// Define the interface for the returned data
export interface GcodeData {
  printTimeHours: number;
  filamentWeightGrams: number;
}

/* -----------------------------------------------------------
    PARSE RAW G-CODE TEXT (Repaired Function)
------------------------------------------------------------ */
export function parseGcode(content: string): GcodeData {
  let filamentWeight = 0;
  let timeHours = 0;

  // --- Filament Weight Extraction ---
  const weightPatterns = [
    // Matches: total filament weight [g]: 12.34
    /total filament weight\s*\[g\]\s*[:=]\s*([\d.]+)/i,
    // Matches: total filament used [g]: 12.34
    /total filament used\s*\[g\]\s*[:=]\s*([\d.]+)/i,
    // Matches: filament used [g]: 12.34
    /filament used\s*\[g\]\s*[:=]\s*([\d.]+)/i,
    // Matches: total filament used: 12.34 g
    /total filament used\s*[:=]\s*([\d.]+)\s*g/i,
    // Matches: filament used: 12.34 g
    /filament used\s*[:=]\s*([\d.]+)\s*g/i,
  ];

  for (const pattern of weightPatterns) {
    const match = content.match(pattern);
    if (match) {
      filamentWeight = parseFloat(match[1]);
      break;
    }
  }

  // --- Time String Extraction ---
  let timeString: string | null = null;
  const timePatterns = [
    /estimated printing time\s*[:=]\s*(.+)/i,
    /estimated time\s*[:=]\s*(.+)/i,
    /; *TIME:\s*(\d+)/i, // Cura seconds
  ];

  for (const pattern of timePatterns) {
    const m = content.match(pattern);
    if (m) {
      timeString = m[1].trim();
      break;
    }
  }

  // --- Time Conversion ---
  if (timeString) {
    if (/^\d+$/.test(timeString)) {
      // Format: Cura seconds (e.g., "7890")
      timeHours = parseInt(timeString, 10) / 3600;
    } else {
      // **BUG FIX HERE:** Use timeString for h/m/s matching, not 'content'
      // Format: 1h 1m 13s, or variants like "3h" or "45m"
      const hMatch = timeString.match(/(\d+)\s*h/i);
      const mMatch = timeString.match(/(\d+)\s*m/i);
      const sMatch = timeString.match(/(\d+)\s*s/i);

      const h = hMatch ? parseFloat(hMatch[1]) : 0;
      const m = mMatch ? parseFloat(mMatch[1]) : 0;
      const s = sMatch ? parseFloat(sMatch[1]) : 0;

      timeHours = h + m / 60 + s / 3600;
    }
  }

  return {
    printTimeHours: timeHours || 0,
    filamentWeightGrams: filamentWeight || 0,
  };
}

/* -----------------------------------------------------------
    PARSE 3MF (Logic remains sound, requires JSZip/File for testing)
------------------------------------------------------------ */
// Requires a 'File' object and actual 'JSZip' implementation
export async function parse3mf(file: File): Promise<GcodeData> {
  const zip = await JSZip.loadAsync(file);

  // Correctly find gcode inside Metadata/
  const gcodePath = Object.keys(zip.files).find(
    (p) => p.startsWith("Metadata/") && p.endsWith(".gcode")
  );

  if (!gcodePath) {
    return { printTimeHours: 0, filamentWeightGrams: 0 };
  }

  // read gcode text
  const gcodeText = await zip.files[gcodePath].async("string");

  // reuse your original parser
  return parseGcode(gcodeText);
}

// --- Example Usage (Demonstration/Testing) ---
const sampleGcode1 = `
; generated by PrusaSlicer 2.4.0
; total filament used [g]: 15.34
; estimated printing time: 1h 45m 30s
G90
`;

const sampleGcode2 = `
; total filament used: 20.01 g
; estimated time: 5400
; TIME: 5400
G90
`;

const result1 = parseGcode(sampleGcode1);
const result2 = parseGcode(sampleGcode2);

console.log("--- Test Case 1 (1h 45m 30s, 15.34g) ---");
console.log(`Time (hours): ${result1.printTimeHours.toFixed(2)}`); // Expected: ~1.76
console.log(`Weight (grams): ${result1.filamentWeightGrams}`); // Expected: 15.34

console.log("\n--- Test Case 2 (5400s, 20.01g) ---");
console.log(`Time (hours): ${result2.printTimeHours.toFixed(2)}`); // Expected: 1.50 (5400/3600)
console.log(`Weight (grams): ${result2.filamentWeightGrams}`); // Expected: 20.01

// Note: To test parse3mf, you would need to set up a file-like object
// and load the JSZip library in your environment.
